# Generated by Django 5.0 on 2024-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseskin',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
