# Generated by Django 5.0 on 2024-04-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkinBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=300)),
                ('rarity_color', models.CharField(max_length=10)),
                ('weapon_type', models.CharField(max_length=20)),
                ('preview_image_url', models.URLField()),
                ('case_container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_skins', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('factory new', 5), ('minimal wear', 21), ('field-tested', 44), ('well-worn', 34), ('battle-scarred', 15), ('stattrak factory new', 1), ('stattrak minimal wear', 3), ('stattrak field-tested', 6), ('stattrak well-worn', 7), ('stattrak battle-scarred', 11)], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('base_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.skinbase')),
            ],
        ),
    ]
