# Generated by Django 5.0 on 2024-04-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinbase',
            name='case_container',
        ),
        migrations.DeleteModel(
            name='Skin',
        ),
        migrations.DeleteModel(
            name='SkinBase',
        ),
    ]
