# Generated by Django 5.0 on 2024-03-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_account_budget_alter_account_date_of_birth_and_more'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkinBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=300)),
                ('rarity_color', models.CharField(max_length=10)),
                ('weapon_type', models.CharField(max_length=20)),
                ('preview_image_url', models.URLField()),
                ('base_case_container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_skins', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('factory new', 'factory new'), ('minimal wear', 'minimal wear'), ('field-tested', 'field-tested'), ('well-worn', 'well-worn'), ('battle-scarred', 'battle-scarred'), ('stattrak factory new', 'stattrak factory new'), ('stattrak minimal wear', 'stattrak minimal wear'), ('stattrak field-tested', 'stattrak field-tested'), ('stattrak well-worn', 'stattrak well-worn'), ('stattrak battle-scarred', 'stattrak battle-scarred')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('base_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.skinbase')),
            ],
        ),
    ]
