# Generated by Django 5.0 on 2024-02-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quality', models.CharField(choices=[('factory new', 'factory new'), ('minimal wear', 'minimal wear'), ('field-tested', 'field-tested'), ('well-worn', 'well-worn'), ('battle-scarred', 'battle-scarred'), ('stattrak factory new', 'stattrak factory new'), ('stattrak minimal wear', 'stattrak minimal wear'), ('stattrak field-tested', 'stattrak field-tested'), ('stattrak well-worn', 'stattrak well-worn'), ('stattrak battle-scarred', 'stattrak battle-scarred')], max_length=30)),
                ('rarity_color', models.CharField(max_length=10)),
                ('weapon_type', models.CharField(max_length=20)),
                ('listings', models.PositiveIntegerField(default=1)),
                ('drop_chance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('preview_image_url', models.URLField()),
                ('case_container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skins', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
