# Generated by Django 5.0 on 2024-03-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinbase',
            old_name='base_case_container',
            new_name='case_container',
        ),
    ]
