# Generated by Django 5.0 on 2024-03-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_budget_alter_account_date_of_birth_and_more'),
        ('cases', '0003_rename_base_case_container_skinbase_case_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
