# Generated by Django 5.0 on 2024-02-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='drop_chance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
