# Generated by Django 5.0 on 2024-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_skin_drop_chance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
